spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/game-team
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful